# Generated by Django 4.2.5 on 2023-09-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.CharField(max_length=39)),
                ("user_agent", models.CharField(max_length=255, null=True)),
                ("accept_language", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name_plural": "Access log entries",
                "ordering": [models.OrderBy(models.F("id"), descending=True)],
            },
        ),
    ]
